### ISSUE TITLE
配网一直失败

### ISSUE THREAD

**Issue by boycezhao** [a2633063/zDC1#12]
用了APP和PC端客户端。
直接连接到DC1的插排控制是正常的。但是就是不能连接到WIFI上。
我另外一个TC1连接正常。DC1有一只正常。是2.4G频段的，可以排队是WIFI的问题。
另外一只怎么操作就是不能连接到WIFI

**Comment by a2633063** [comment]
pc端由于软件bug  使用pc端配对时 请禁用其他所有网卡(包括虚拟网卡)  后面修复此问题

**Comment by boycezhao** [comment]
已经禁用所有网卡，只留一个无线网卡。还是配网不成功。
会不会和WIFI热点名字有关系。热点的名字是：X_Y_2.4
但是之前的DC1和TC1又是能正常连接的

**Comment by a2633063** [comment]
v1.3.0及以后版本使用web配网 修复使用smartconfig配网不支持部分路由器导致配网失败的问题
