### ISSUE TITLE
接入百度云clientid有中文无效

### ISSUE THREAD

**Issue by stscor** [a2633063/zDC1#13]
使用百度云数据型iot作为mqtt服务器时，设备使用名称作为clientid，当名称中有中文时就会提示invalid id，建议设备能自定义client id或者使用mac地址作为client id。

**Comment by a2633063** [comment]
本身设计是以mac作为clientid  刚刚看了代码 可能是手误 目前是将设备名作为clientid了  之前没有注意此问题
下个更新版本修改为mac(此为小问题所以不为了这个专门出一个版本了,下次修复其他问题发布时一起修复此问题)
你可以将设备名称改为不带中文应该可以先支持百度云iot
