### ISSUE TITLE
zdc1升级最新版本配网不了

### ISSUE THREAD

**Issue by hwatery** [a2633063/zDC1#17]
app版本，1.4.5
固件版本：1.3.2

昨天从把dc1 从v0.2.1  在app1.4.5上检测新版本提示升级到到1.3.2 点升级，等了好久，就开始配网，配不成功。长按过10s以上，应该重置了插排了，试过2次配网都不行，用连接dc的热点，手机或者电脑连接热点后，网页输入192.168.0.1 ，网页打不开，提示拒绝。  用第二种方法也是配对不了。。。 这该咋操作呢

**Comment by a2633063** [comment]
可能被升级为1.0.1版本 请使用旧版本配网方式配网

**Comment by hwatery** [comment]
> 可能被升级为1.0.1版本请使用旧版本配网方式配网

下载旧版本的app 在上面配网？

**Comment by a2633063** [comment]
> > 可能被升级为1.0.1版本请使用旧版本配网方式配网
> 
> 下载旧版本的app 在上面配网？

当前新版app还支持旧版配网, 在app新增设备页面选择dc1 里面有配网说明 按照SmartConfig的配网方式配网即可

**Comment by hwatery** [comment]
> > > 可能被升级为1.0.1版本请使用旧版本配网方式配网
> > 
> > 
> > 下载旧版本的app在上面配网？
> 
> 当前新版app还没有支持旧版配网，在app添加设备页面选择dc1里面有配网说明按照SmartConfig的配网方式配网即可

smart comfig  这个配网方式 我试过了， 我wifi名称 2L-DT_2.4G ， 按照那教程 输入密码   点配对，就是配对不成功， 下面2个选项 都试过了，就是配对不了。不知道咋回事。

**Comment by a2633063** [comment]
smartconfig的配网对于部分路由器/ssid支持不太好,这也是最新固件增加web配网的原因.
建议您用其他手机开个2.4g热点,ssid及密码别包含特殊字符只包含小写字母即可,然后用smartconfig配网,配网完成后用ota升级到最新版本.之后即可用热点配网
