### ISSUE TITLE
怎么OTA？ 没找到教程。

### ISSUE THREAD

**Issue by happylgs** [a2633063/zDC1#3]
怎么OTA？ 没找到教程。

**Comment by a2633063** [comment]
设备页面，直接点版本号即可ota

**Comment by happylgs** [comment]
这个版本如果不用MQTT 无法连接homeassistant吗？

**Comment by a2633063** [comment]
必须通过MQTT连入

**Comment by wolfid1** [comment]
> *，*太奥



> 设备页面，直接点版本号即可ota

设备页面怎么进呢。。没找到。。。。。
