### ISSUE TITLE
ssid里面带-是不是不能连网？

### ISSUE THREAD

**Issue by qxwo** [a2633063/zDC1#5]
用cmcc-xxx的路由配对不上，用全英文的就可以了。。。
刚入坑有些功能问下
离线能否关闭电源
断电重连默认是记忆上一次的断电情况，能否恢复电后固定开关状况。

谢谢大佬提供的固件，很好用。

**Comment by qxwo** [comment]
断网后好像无法重连，本来状态正常，重启路由后插排MQTT里没有插排，断电插排后又可以，是个例吗？

**Comment by yylwhy** [comment]
亲测带  -   可以配网
