### ISSUE TITLE
有没考虑过会不会开源的啊？

### ISSUE THREAD

**Issue by sonwa** [a2633063/zDC1#6]
如题

**Comment by Cp0204** [comment]
作者说过，等库存消化得差不多了，会考虑。避免辛辛苦苦写的固件，被商家拿来敛财。

**Comment by sonwa** [comment]
好的“圣人”。当时只是有个问题没解决想看看是怎样实现的，不过现在解决了。下个月出个半开源代码版，不管是商家还是普通人，只要你是人就可以免费使用，没任何限制版！更不需要耍流氓的激活码

**Comment by a2633063** [comment]
半开源代码版?
还是欢迎开源开发,共同学习

**Comment by sonwa** [comment]
开源开发？
你的全闭源放出来还开源开发？

**Comment by a2633063** [comment]
我是说出个半开源代码版 有点不懂....
我本身是开源开发,因为商家不良商用才闭源了.我等以后看看情况再开源吧

**Comment by sonwa** [comment]
就是方便调用打包成库，不过大部份源码都会写在主文件内
可以透露一下，支持mqtt但不支持Home Assistant，直接接入另一个物联网平台，还支持天猫精灵控制
app就正好和你相反吧，只支持iOS，暂不支持Android

**Comment by a2633063** [comment]
哦哦 
好奇下 支持mqtt为什么不支持hass 支持mqtt应该就能接入hass啊
物联网平台倒不是什么难事,我自己用不上才没做.......
个人开发的ios吗 相对来说开发ios比开发android成本高吧..

**Comment by sonwa** [comment]
平台都是自己弄的，主要是平台弄好了没什么可以接入测试，刚好看新闻这个可以自制固件，拿这个下手了。用第三方平台很怕他融资不行就倒闭，就像这个排插没了服务器废了。我弄这个平台程序可以装上自己的服务器上，不用怕服务器不可用
Home Assistant很早之前玩过下，操作起来有些烦琐后续不好扩展
所以还是直接自己弄个平台玩起来方便，还有对接起身市面上的音箱比较方便。什么小度在家，小爱同学乱七八糟的音箱都可以打通控制。
iOS是个人开发成本不高，正在设计个简单的控制界面UI，切好片，开发起身都好快

**Comment by jjss520** [comment]
要有IOS版的了吗？ios的一直用HA，不太喜欢HA，脚肿，服务器内存占用大

**Comment by a2633063** [comment]
平台完全是自己写的吗...
hass确实很繁琐,不过现在也只有这个能用下了.本来也考虑自己写,但是实在没那个时间精力了.
ios个人开发成本不高也需要费用申请开发者吧 除非不上架? 或是本身就是ios的开发人员了~
我也在考虑如何比较好的解决ios和android端. 家人想换ios,但是这样我写的工具她就用不了了,所有也看了微信小程序和QQ小程序,发现还是有瑕疵.
目前我是个人主要使用app,使用mqtt通信,并不经过hass.
目前主要问题还是没有好的服务器给大家使用,局域网使用udp广播很不稳定,我自己使用mqtt也不会去好好优化局域网通信.
其实如果你固件完美方便的话肯定也会被那些商家直接拿去商用,不过你个人不介意就无所谓.
反正我是有点不爽,所以才弄了激活码限制下商用,也知道影响部分个人使用,不过也是没办法了.
本身最开始也并没有想给所有人使用,而是给有点技术能够折腾的人使用,问题比较少,我能比较省心了.

**Comment by sonwa** [comment]
嗯，平台都是自己写的。用了我一年业余时间开发的...
我本身做后端和iOS开发的，所以iOS证书方便不是问题，平台的调试工具已经上架了。兴趣问题现在都把模块固件干上了...
后续可能都会弄个小程序，不过用小程序有配网绑定设备问题，这个迟下再研究下
其实我弄这个不做限制有点私心吧，就是想更多人接入用下我开发的平台，等收集下意见改进，为以后加AI做准备。
这些都是个人业余时间弄的，个人弄有些功能考虑可能不周所以放出去等多些人用收集意见改良。

**Comment by a2633063** [comment]
平台现在提供资料之类的吗~
我也可以看看,如果方便也可以一起使用啊~

**Comment by a2633063** [comment]
> 要有IOS版的了吗？ios的一直用HA，不太喜欢HA，脚肿，服务器内存占用大

还是没有  不过ios有人做了个 没有签名 所有要每7天自签一次 麻烦点 但是能用
而且说真的 比我的app好看多了
https://github.com/HuaZao/TC1-NG

**Comment by sonwa** [comment]
网站弄了一个，写了几个使用安装教程 https://bbs.daxunyun.com/
文档接口 https://doc.daxunyun.com/
打算弄完这个排插会更新一下接口文档，后端可能都会有些修改，之前一直以单品方式设计，在弄这个排插时发现有小小要修改

**Comment by a2633063** [comment]
只能通过mqtt接入啊T.T
这就有点不合理了  还有很多设备是只能劫持之类的比如小米  不可能让他们去改的....

**Comment by sonwa** [comment]
0.0还没考虑到正常使用连接服务器的设备改他连接
但设备想使用小米的小爱音箱可以通过云云对接打通控制，精力有限现在暂时只对了天猫

**Comment by a2633063** [comment]
小米的小爱音箱接入必须以公司名义接入  个人是无法接入的
一般用平台的更多考虑自动化实现,这方面才是重点

**Comment by sonwa** [comment]
对，小米比较反人类只能以公司名义接入，天猫可以个人接入调试
嗯，自动化是实现是比较重要，可以简化步骤和减小出错

**Comment by sonwa** [comment]
基于上次博主共同学习的思想，固件直接全开源。不过还差定时，近排的事比较多暂时没时间加。
可以的话博主分享一份定时源码给我加上去？:P
用iOS直接控制，商城可以直接下。不过服务器要自己装一下，安装还是比较简单 ^o^
源码地址看新贴

**Comment by a2633063** [comment]
有准备开源了  不过打算删除激活码的相关代码后再开源 所以需要稍等一段时间了.
预计1月份完成.这段时间比较忙  空闲时间比较少

定时实际上就是获取sntp时间 然后等待时间到就开关插座而已,没有什么特殊的
