### ISSUE TITLE
路由器更换SSID后无法重新配网

### ISSUE THREAD

**Issue by ghost** [a2633063/zDC1#7]
家里升级路由器后，改了路由器无线SSID，插排长按10s至LOGO灯闪烁恢复默认，我再按照说明步骤长按按键5s至LOGO灯常亮但是重新配网不成功，这种情况需要再拆机重新刷吗？

**Comment by ghost** [comment]
不好意思点错了，重开了，我换了路由器后，改了路由器无线SSID，插排长按10s至LOGO灯闪烁恢复默认，我再按照说明步骤长按按键5s至LOGO灯常亮但是重新配网不成功，这种情况需要再拆机重新刷吗？DC1插排，之前已经激活了。

**Comment by a2633063** [comment]
不用重刷
是不是刷机的固件有阉割导致配网失败
可以先试试其他路由器

**Comment by ghost** [comment]
感谢解答，今天我把另一个也恢复默认设置了，长按10s后LOGO闪烁，然后我松开按键灯就都灭了，没有自动重启，长按5s可以点亮LOGO灯但也是无法配网。另外已经换过路由器实验，恢复默认前能正常连接，恢复默认后无法连接。

**Comment by ghost** [comment]
我刚刚翻出我的K2路由器重新试了下配网成功了，，明明同一个版本的固件，但是K2P和新路由3都不行，不过问题解决了，再次感谢大佬。

**Comment by a2633063** [comment]
v1.0.2已经更换为web配网.

**Comment by a2633063** [comment]
v1.3.0之后版本增加web配网 修复smartconfig配网兼容性不好无法配网的问题
