### ISSUE TITLE
再次掉激活

### ISSUE THREAD

**Issue by jjss520** [a2633063/zDC1#8]
第一次，正常使用了很久，早上突然不能控制，还以为是电源的问题，重新重启也不行，长按按键也不行，在网络里看，联网了，开始以为要重新刷固件，然后在APP里查看，未激活，然后找出激活码重新激活，正常，昨天又发现掉了激活，然后激活后正常使用，不知道是哪里的问题

**Comment by a2633063** [comment]
dc1是有这个bug   后面会一起完成此问题

**Comment by jjss520** [comment]
好的，还以为是个例，早日更新

**Comment by a2633063** [comment]
问题未解, issue reopen

**Comment by jjss520** [comment]
> 问题未解，问题重新开放

老大，快更新呀，最近老是掉激活

**Comment by a2633063** [comment]
麻烦确认一下 掉激活后排插是否依然和mqtt服务器连接,还是mqtt服务器也断开了

**Comment by a2633063** [comment]
临时release一般不需要激活的版本:https://github.com/a2633063/zDC1_public/releases/tag/v0.2.3

请长按版本号 输入以下内容ota: (输入后应该为2行内容,每行一个链接,请不要带有其他多余的字符)
```
http://zipzhang.top/zDC1/v0.2.3/user1.1024.new.2.bin
http://zipzhang.top/zDC1/v0.2.3/user2.1024.new.2.bin
```

**Comment by jjss520** [comment]
> 临时版本一般不需要激活的版本：[https](https://github.com/a2633063/zDC1_public/releases/tag/v0.2.3) : [//github.com/a2633063/zDC1_public/releases/tag/v0.2.3](https://github.com/a2633063/zDC1_public/releases/tag/v0.2.3)
> 
> 请长按版本号输入以下内容ota：（输入后应该为2行内容，每行一个链接，请不要带有其他多余的字符）
> 
> ```
> http://zipzhang.top/zDC1/v0.2.3/user1.1024.new.2.bin
> http://zipzhang.top/zDC1/v0.2.3/user2.1024.new.2.bin
> ```

在软件里输入了地址，软件闪一下，然后就没然后了，好像是没开始更新

**Comment by a2633063** [comment]
> > 临时版本一般不需要激活的版本：[https](https://github.com/a2633063/zDC1_public/releases/tag/v0.2.3) : [//github.com/a2633063/zDC1_public/releases/tag/v0.2.3](https://github.com/a2633063/zDC1_public/releases/tag/v0.2.3)
> > 请长按版本号输入以下内容ota：（输入后应该为2行内容，每行一个链接，请不要带有其他多余的字符）
> > ```
> > http://zipzhang.top/zDC1/v0.2.3/user1.1024.new.2.bin
> > http://zipzhang.top/zDC1/v0.2.3/user2.1024.new.2.bin
> > ```
> 
> 在软件里输入了地址，软件闪一下，然后就没然后了，好像是没开始更新

有成功吗 输入是否带有其他换行什么的..

**Comment by jjss520** [comment]
> > > 临时版本一般不需要激活的版本：[https](https://github.com/a2633063/zDC1_public/releases/tag/v0.2.3)：[//github.com/a2633063/zDC1_public/releases/tag/v0.2.3](https://github.com/a2633063/zDC1_public/releases/tag/v0.2.3) 
> > > 请长按版本号输入以下内容ota ：（输入后应该为2行内容，每行一个链接，请不要带有其他多余的字符）
> > > ```
> > > http://zipzhang.top/zDC1/v0.2.3/user1.1024.new.2.bin
> > > http://zipzhang.top/zDC1/v0.2.3/user2.1024.new.2.bin
> > > ```
> > 
> > 
> > 在软件里输入了地址，软件闪一下，然后就没然后了，好像是没开始更新
> 
> 有成功吗输入是否带有其他换行什么的..

没成功，不知道怎么回事，输入地址，软件闪一下就回到了控制界面

**Comment by jjss520** [comment]
直接点击检查更新，也不行，输入地址也不行

**Comment by a2633063** [comment]
> > > > 临时版本一般不需要激活的版本：[https](https://github.com/a2633063/zDC1_public/releases/tag/v0.2.3)：[//github.com/a2633063/zDC1_public/releases/tag/v0.2.3](https://github.com/a2633063/zDC1_public/releases/tag/v0.2.3)
> > > > 请长按版本号输入以下内容ota ：（输入后应该为2行内容，每行一个链接，请不要带有其他多余的字符）
> > > > ```
> > > > http://zipzhang.top/zDC1/v0.2.3/user1.1024.new.2.bin
> > > > http://zipzhang.top/zDC1/v0.2.3/user2.1024.new.2.bin
> > > > ```
> > > 
> > > 
> > > 在软件里输入了地址，软件闪一下，然后就没然后了，好像是没开始更新
> > 
> > 
> > 有成功吗输入是否带有其他换行什么的..
> 
> 没成功，不知道怎么回事，输入地址，软件闪一下就回到了控制界面

测试了下 mqtt服务器下没有问题
局域网下可能因为udp通信不稳定出现偶尔无效的情况  可以多试几次

**Comment by jjss520** [comment]
> > > > > 临时版本一般不需要激活的版本：[https](https://github.com/a2633063/zDC1_public/releases/tag/v0.2.3)：[//github.com/a2633063/zDC1_public/releases/tag/v0.2.3](https://github.com/a2633063/zDC1_public/releases/tag/v0.2.3)
> > > > > 请长按版本号输入以下内容ota ：（输入后应该为2行内容，每行一个链接，请不要带有其他多余的字符）
> > > > > ```
> > > > > http://zipzhang.top/zDC1/v0.2.3/user1.1024.new.2.bin
> > > > > http://zipzhang.top/zDC1/v0.2.3/user2.1024.new.2.bin
> > > > > ```
> > > > 
> > > > 
> > > > 在软件里输入了地址，软件闪一下，然后就没然后了，好像是没开始更新
> > > 
> > > 
> > > 有成功吗输入是否带有其他换行什么的..
> > 
> > 
> > 没成功，不知道怎么回事，输入地址，软件闪一下就回到了控制界面
> 
> 测试了下 mqtt服务器下没有问题
> 局域网下可能因为udp通信不稳定出现偶尔无效的情况 可以多试几次

MQTT下和UDP下都测试了很多次，输入网址确认后，软件闪一下，又回到排插的界面，没任何反应，点击检查更新，也是无更新，这个你可以在服务上更新吗，这样我点击更新就行，主要是老是掉激活，里面的定时任务没了，而且在外面想控制，掉了激活也不行

**Comment by a2633063** [comment]
> > > > > > 临时版本一般不需要激活的版本：[https](https://github.com/a2633063/zDC1_public/releases/tag/v0.2.3)：[//github.com/a2633063/zDC1_public/releases/tag/v0.2.3](https://github.com/a2633063/zDC1_public/releases/tag/v0.2.3)
> > > > > > 请长按版本号输入以下内容ota ：（输入后应该为2行内容，每行一个链接，请不要带有其他多余的字符）
> > > > > > ```
> > > > > > http://zipzhang.top/zDC1/v0.2.3/user1.1024.new.2.bin
> > > > > > http://zipzhang.top/zDC1/v0.2.3/user2.1024.new.2.bin
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 在软件里输入了地址，软件闪一下，然后就没然后了，好像是没开始更新
> > > > 
> > > > 
> > > > 有成功吗输入是否带有其他换行什么的..
> > > 
> > > 
> > > 没成功，不知道怎么回事，输入地址，软件闪一下就回到了控制界面
> > 
> > 
> > 测试了下 mqtt服务器下没有问题
> > 局域网下可能因为udp通信不稳定出现偶尔无效的情况 可以多试几次
> 
> MQTT下和UDP下都测试了很多次，输入网址确认后，软件闪一下，又回到排插的界面，没任何反应，点击检查更新，也是无更新，这个你可以在服务上更新吗，这样我点击更新就行，主要是老是掉激活，里面的定时任务没了，而且在外面想控制，掉了激活也不行

可以直接ota了
